# Generated by Django 4.1.1 on 2022-09-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0003_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_price', models.FloatField()),
                ('book_quantity', models.PositiveIntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_value', models.CharField(choices=[('NEW', 'new'), ('CONFIRMED', 'confirmed'), ('CANCELLED', 'cancelled'), ('COMPLETED', 'completed')], default='NEW', max_length=200)),
            ],
        ),
    ]
