# Generated by Django 4.1.1 on 2022-09-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_manager'),
        ('books', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [

    ]
