# Generated by Django 4.1.1 on 2022-09-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_manager'),
        ('books', '0001_initial'),
        ('orders', '0002_customerorder_full_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('full_price', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='users.customer')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.orderstatus')),
                ('ordered_books', models.ManyToManyField(to='books.book')),
            ],
        ),
    ]
