# Generated by Django 4.1.1 on 2022-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_customerorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='full_price',
            field=models.FloatField(default=1.0),
        ),
    ]
