# Generated by Django 4.1.1 on 2023-01-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_customerorder_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status_value',
            field=models.CharField(choices=[('NEW', 'new'), ('CONFIRMED', 'confirmed'), ('CANCELLED', 'cancelled'), ('COMPLETED', 'completed'), ('ILLEGIBLE', 'illegible')], default='NEW', max_length=200),
        ),
    ]
