# Generated by Django 4.1.1 on 2023-01-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderstatus_status_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstate',
            name='sold_copy_number',
            field=models.IntegerField(default=0),
        ),
    ]
